# Generated by Django 5.1.7 on 2025-03-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_debut_booking', models.DateField()),
                ('heure', models.TimeField()),
            ],
        ),
    ]
