# Generated by Django 5.1.7 on 2025-03-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='numero_reservation',
            field=models.CharField(default='XXXXX', max_length=10, unique=True),
        ),
    ]
