# Generated by Django 5.1.7 on 2025-03-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_numero_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='numero_reservation',
            field=models.CharField(blank=True, default='XXXXX', editable=False, max_length=5, unique=True),
        ),
    ]
