# Generated by Django 5.1.7 on 2025-03-27 22:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_numero_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='numero_reservation',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=10, null=True, unique=True),
        ),
    ]
